In [1]:
### finding eigen values and eigen vectors

In [4]:
import numpy as np

matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])
matrix

array([[ 1, -1,  3],
       [ 1,  1,  6],
       [ 3,  8,  9]])

In [7]:
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [8]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [9]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

In [10]:
#Adding and Subtracting Matrices
# Load library

import numpy as np

# Create matrix
matrix_a = np.array([[1, 1, 1],
[1, 1, 1],
[1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
[1, 3, 1],
[1, 3, 8]])


In [11]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [12]:
matrix_a-matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [15]:
### Inverting a Matrix
#Create matrix
matrix = np.array([[1, 4],
                  [2, 5]])


In [16]:
# Calculate inverse of matrix
np.linalg.inv(matrix)


array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [17]:
#### identity matrix
# Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [18]:
#### Generating Random Values
# Set seed
np.random.seed(0)
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [20]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 5)

array([ 1.96992445,  1.26611853, -0.50587654,  2.54520078,  1.08081191])

####  Data Wrangling

In [31]:
####Creating a Data Frame

# Load library
import pandas as pd

# Create DataFrame
dataframe = pd.DataFrame()

# Add columns
dataframe['Name'] = ['Jacky Jackson', 'Steven Stevenson']
dataframe['Age'] = [38, 25]
dataframe['Driver'] = [True, False]

# Show DataFrame
dataframe


Index(['Name', 'Age', 'Driver'], dtype='object')

In [32]:
#### append a new row

# Create row
new_person = pd.Series(['Molly Mooney', 40, True], index=[dataframe.columns
new_person

SyntaxError: invalid syntax (<ipython-input-32-6f67f2c76ca0>, line 5)

In [25]:
#### now append
# Append row
dataframe.append(new_person, ignore_index=True)

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False
2      Molly Mooney   40    True