In [6]:
## Fitting a Line

# Load libraries
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

# Load data with only two features
boston = load_boston()
features = boston.data[:,0:2]
target = boston.target

In [7]:
# Create linear regression
regression = LinearRegression()

# Fit the linear regression
model = regression.fit(features, target)

In [8]:
# View the intercept
model.intercept_

22.485628113468223

In [9]:
# View the feature coefficients
model.coef_

array([-0.35207832,  0.11610909])

In [10]:
#### Using the predict method, we can predict a value for that house:

# Predict the target value of the first observation, multiplied by 1000
model.predict(features)[0]*1000

24573.366631705547

In [11]:
###  Handling Interactive Effects

### You have a feature whose effect on the target variable depends on another
###feature.

# Load libraries
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures

In [12]:
# Load data with only two features
boston = load_boston()
features = boston.data[:,0:2]
target = boston.target

In [14]:
# Create interaction term
interaction = PolynomialFeatures(
degree=3, include_bias=False, interaction_only=True)
features_interaction = interaction.fit_transform(features)
features_interaction

array([[6.3200e-03, 1.8000e+01, 1.1376e-01],
       [2.7310e-02, 0.0000e+00, 0.0000e+00],
       [2.7290e-02, 0.0000e+00, 0.0000e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 0.0000e+00],
       [1.0959e-01, 0.0000e+00, 0.0000e+00],
       [4.7410e-02, 0.0000e+00, 0.0000e+00]])

In [15]:
# Create linear regression
regression = LinearRegression()

# Fit the linear regression
model = regression.fit(features_interaction, target)

In [16]:
# View the feature values for first observation
features[0]

array([6.32e-03, 1.80e+01])

In [24]:
# Import library
import numpy as np

# For each observation, multiply the values of the first and second feature
interaction_term = np.multiply(features[:, 0], features[:, 1])

In [19]:
# View interaction term for first observation
interaction_term[0]

0.11376

In [20]:
# View the values of the first observation
features_interaction[0]

array([6.3200e-03, 1.8000e+01, 1.1376e-01])

In [25]:
###  Fitting a Nonlinear Relationship

##You want to model a nonlinear relationship
# Load library
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures

In [26]:
# Load data with one feature
boston = load_boston()
features = boston.data[:,0:1]
target = boston.target

In [30]:
# Create polynomial features x^2 and x^3
polynomial = PolynomialFeatures(degree=3, include_bias=False)
features_polynomial = polynomial.fit_transform(features)

In [31]:
# Create linear regression
regression = LinearRegression()

# Fit the linear regression
model = regression.fit(features_polynomial, target)

In [32]:
# View the first observation's values for x, x^2, and x^3
features_polynomial[0]

array([6.32000000e-03, 3.99424000e-05, 2.52435968e-07])

In [33]:
###  Reducing Variance with Regularization

#You want to reduce the variance of your linear regression model.

# Load libraries
from sklearn.linear_model import Ridge
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

In [34]:
# Load data
boston = load_boston()
features = boston.data
target = boston.target

In [35]:
# Standardize features
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

In [36]:
# Create ridge regression with an alpha value
regression = Ridge(alpha=0.5)

# Fit the linear regression
model = regression.fit(features_standardized, target)

In [37]:
### scikit-learn includes a RidgeCV method that allows us to select the ideal value
##for α:

# Load library
from sklearn.linear_model import RidgeCV

# Create ridge regression with three alpha values
regr_cv = RidgeCV(alphas=[0.1, 1.0, 10.0])

# Fit the linear regression
model_cv = regr_cv.fit(features_standardized, target)

# View coefficients
model_cv.coef_

array([-0.91987132,  1.06646104,  0.11738487,  0.68512693, -2.02901013,
        2.68275376,  0.01315848, -3.07733968,  2.59153764, -2.0105579 ,
       -2.05238455,  0.84884839, -3.73066646])

In [38]:
###  Reducing Features with Lasso Regression

# Load library
from sklearn.linear_model import Lasso
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

In [39]:
# Load data
boston = load_boston()
features = boston.data
target = boston.target

In [42]:
# Standardize features
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

# Create lasso regression with alpha value
regression = Lasso(alpha=0.5)

# Fit the linear regression
model = regression.fit(features_standardized, target)

# View coefficients
model.coef_


array([-0.11526463,  0.        , -0.        ,  0.39707879, -0.        ,
        2.97425861, -0.        , -0.17056942, -0.        , -0.        ,
       -1.59844856,  0.54313871, -3.66614361])

In [43]:
# Create lasso regression with a high alpha
regression_a10 = Lasso(alpha=10)
model_a10 = regression_a10.fit(features_standardized, target)
model_a10.coef_

array([-0.,  0., -0.,  0., -0.,  0., -0.,  0., -0., -0., -0.,  0., -0.])